apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-
namespace: bookstore-prod

resources:
  - ../../base

patches:
  - path: replica-patch.yaml
  - path: resources-patch.yaml
